import {test} from 'node:test';
import assert from 'node:assert/strict';
import {run,initialState} from '../server/domain.mjs';
const seed=()=>({...initialState(),members:['master','admin','crew','member','guest'].map(userId=>({userId,displayName:userId,email:userId+'@test.invalid'})),roles:{master:'master',admin:'admin',crew:'crew',member:'member',guest:'guest'},drinks:[{id:'beer',name:'Bier',pack:24,price:200,purchasePrice:100,active:1}]});
const cmd=(action,args={})=>({action,requestId:crypto.randomUUID(),...args});
test('Bestand ausschließlich Admin/Master; Crew und Mitglieder auch per API gesperrt',async()=>{let s=seed();for(const role of ['crew','member','guest'])await assert.rejects(run(s,role,cmd('stock',{items:[{id:'beer',cases:1,bottles:0}]})));s=(await run(s,'admin',cmd('stock',{items:[{id:'beer',cases:1,bottles:0}]}))).state;for(const role of ['crew','member','guest'])assert.equal((await run(s,role)).body.stock.length,0);assert.equal((await run(s,'master')).body.stock.length,1)});
test('Termin anfragen als Crew/Mitglied/Gast; nur Admin/Master bestätigt; private Notizen nur eigene',async()=>{let s=seed();for(const role of ['crew','member','guest'])s=(await run(s,role,cmd('requestRental',{day:'2099-02-01',note:'Private Notiz '+role,status:'confirmed'}))).state;assert(s.rentals.every(r=>r.status==='requested'));for(const role of ['crew','member','guest']){const view=(await run(s,role)).body;assert.equal(view.rentals.length,role==='guest'?1:3);assert.equal(view.rentals.filter(r=>r.notes).length,1);assert.equal(view.rentals.find(r=>r.own).notes,'Private Notiz '+role);await assert.rejects(run(s,role,cmd('saveRental',{...s.rentals[0],status:'confirmed'})));await assert.rejects(run(s,role,cmd('requestRental',{day:'2099-02-01',note:'Doppelt'})));}const r=s.rentals.find(r=>r.requestedBy==='guest');s=(await run(s,'admin',cmd('saveRental',{...r,status:'confirmed',acceptConflicts:true}))).state;assert.equal((await run(s,'guest')).body.rentals[0].status,'confirmed');await assert.rejects(run(s,'member',cmd('requestRental',{day:'2099-02-30',note:'Falsch'})));});
test('Dauerhafte Infos: Zielgruppen serverseitig gefiltert, nur Verwaltung schreibt',async()=>{let s=seed();for(const audience of ['crew','member','both'])s=(await run(s,'admin',cmd('saveInfo',{title:audience,text:'Info '+audience,audience}))).state;for(const role of ['crew','member']){const rows=(await run(s,role)).body.infos;assert.equal(rows.length,2);assert(rows.every(r=>r.audience===role||r.audience==='both'));await assert.rejects(run(s,role,cmd('saveInfo',{title:'X',text:'X',audience:'both'})));await assert.rejects(run(s,role,cmd('deleteInfo',{id:s.infos[0].id})));}assert.equal((await run(s,'guest')).body.infos.length,0);assert.equal((await run(s,'master')).body.infos.length,3);const id=s.infos[0].id;s=(await run(s,'master',cmd('saveInfo',{id,title:'Neu',text:'Dauerhaft',audience:'crew'}))).state;assert.equal(s.infos.length,3);assert.equal(s.infos[0].text,'Dauerhaft')});
test('Gäste/Mitglieder können sich nicht für Personal bewerben; Tagesspecial für alle Rollen',async()=>{let s=seed();for(const role of ['guest','member'])await assert.rejects(run(s,role,cmd('applyEvent',{event:s.events[0].id,duty:'Theke'})));s=(await run(s,'admin',cmd('saveSpecial',{title:'Spritz',description:'Special',price:500,day:'2099-01-01'}))).state;for(const role of ['guest','member','crew','admin','master'])assert.equal((await run(s,role)).body.special.title,'Spritz')});
