import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import assert from 'node:assert/strict';
import {FeatureSettings,InventoryAccounts,MemberAccounts,OwnAccount} from '../src/management';
import Rentals from '../src/rentals';
import {GuestHome,BottomNav,CrewHome} from '../src/experience';
import RecapPortal from '../src/recap-portal';
import EventBoard from '../src/event-board';
import {initialState,run} from '../server/domain.mjs';
const state={...initialState(),members:['master','admin','crew','member','guest'].map(userId=>({userId,displayName:userId,email:userId+'@test.org'})),roles:{master:'master',admin:'admin',crew:'crew',member:'member',guest:'guest'},events:[{id:'event',name:'Testband',day:'2020-01-10'}],rentals:[{id:'r',name:'Privatkunde',phone:'+4912345678',start:'2027-01-01T18:00',end:'2027-01-01T23:00',status:'requested',notes:'Notiz'}],eventAccounts:[{event:'event',eventName:'Testband',eventDay:'2020-01-10',profit:-3400,closed:true}],accountEntries:[{id:'credit',kind:'help',user:'crew',amount:5000,hours:5,date:'2020-01-11T12:00:00Z'}]};
const act=()=>{},confirm=()=>{},go=()=>{};
for(const role of ['master','admin','crew','member','guest']){const data=(await run(state,role)).body;const nav=renderToStaticMarkup(<BottomNav data={data} tab="home" go={go}/>);assert(!nav.includes('Todo’s'));assert(!nav.includes('Social'));assert.equal(nav.includes('Admin'),['master','admin'].includes(role));assert.equal(renderToStaticMarkup(<RecapPortal data={data}/>),'');const events=renderToStaticMarkup(<EventBoard data={data} act={act} busy={false}/>);assert(!events.includes('RÜCKBLICK'));assert.equal(events.includes('Crew-Infos'),data.staff);if(data.guest){const guest=renderToStaticMarkup(<GuestHome data={data} go={go}/>);assert(!guest.includes('Social Wall'));assert(!guest.includes('Rückblicke'));assert(guest.includes('Getränkekarte'))}if(data.staff){const crew=renderToStaticMarkup(<CrewHome data={data} go={go}/>);assert(!crew.includes('Offene Todo’s'))}if(data.admin){const rentals=renderToStaticMarkup(<Rentals data={data} act={act} busy={false}/>);assert(rentals.includes('Privatkunde'));assert(rentals.includes('Vermietungen'));}if(data.master){const settings=renderToStaticMarkup(<FeatureSettings data={data} act={act} busy={false}/>);assert(settings.includes('Funktionen freischalten'));assert.equal((settings.match(/role="switch"/g)||[]).length,8);const bill=renderToStaticMarkup(<InventoryAccounts data={data} act={act} busy={false} confirm={confirm}/>);assert(bill.includes('Verlust'));assert(bill.includes('class="loss"'));const accounts=renderToStaticMarkup(<MemberAccounts data={data} act={act} busy={false} confirm={confirm}/>);assert(accounts.includes('Helfereinsätze bestätigen'));assert(accounts.includes('50,00'));}if(role==='crew'){assert(renderToStaticMarkup(<OwnAccount data={data}/>).includes('50,00'));}}
console.log('Renderprüfung bestanden: fünf Rollen, Schalter, Navigation, Vermietungen, Konten und Gewinngrafik.');
