import {seedEvents,SOURCE_CHECKED,mergeEvents} from './event-seed.mjs';
export const duties=['Theke','Parkplatz','Ton','Licht','Eintritt','Joker'];
export function initialState(){return {members:[],roles:{},drinks:[],shopping:[],tallies:[],records:[],events:structuredClone(seedEvents),notes:[],corrections:[],applications:[],eventSync:SOURCE_CHECKED}}
export async function run(state,active,command){
let output=structuredClone(state);const readState=()=>output;const writeState=s=>{output=s};
if(!output.members.some(x=>x.userId===active))throw Error('Kein Mitgliedskonto vorhanden.');
function num(v,max=100000){if(!Number.isSafeInteger(v)||v<0||v>max)throw Error('Bitte eine gültige ganze Anzahl eingeben.');return v}
function str(v){if(typeof v!=='string'||!v.trim()||v.length>300)throw Error('Bitte einen gültigen Text eingeben.');return v.trim()}
async function apiFetch(url,options={}){try{
if(url==='/api/events'){const s=readState();return reply({events:s.events,checked:s.eventSync})}
if(url!=='/api/crew')throw Error('Unbekannte Anfrage');const s=readState(),u=s.members.find(x=>x.userId===active),admin=['admin','master'].includes(s.roles[active]),master=s.roles[active]==='master';
if(!options.method||options.method==='GET')return reply({user:u,admin,master,setup:false,corrections:s.corrections.filter(x=>master||x.user===active),events:s.events,notes:s.notes,applications:s.applications.filter(x=>admin||x.user===active),eventSync:s.eventSync,drinks:s.drinks.filter(x=>x.active).sort((a,b)=>a.name.localeCompare(b.name)),shopping:s.shopping.filter(x=>!x.done),stock:s.records.filter(x=>x.kind==='stock').slice().reverse(),tallies:s.tallies.filter(x=>!x.receipt&&!x.void&&(master||x.user===active)),people:master?s.members.map(x=>({id:x.userId,name:x.displayName,email:x.email,role:s.roles[x.userId]||'crew'})):[],allocations:master?s.records.filter(x=>x.kind==='allocation').slice().reverse():[],receipts:master?s.records.filter(x=>x.kind==='receipt').slice().reverse():[],orders:admin?s.records.filter(x=>x.kind==='order').slice().reverse():[]});
const b=JSON.parse(options.body),id=b.requestId||crypto.randomUUID(),now=new Date().toISOString();
if(['drink','archiveDrink','order','done','syncEvents','decideApplication'].includes(b.action)&&!admin)throw Error('Bitte zum Admin-Konto wechseln.');
if(['settle','allocate','receipt','assignRole','resolveCorrection','resetAll','saveMember'].includes(b.action)&&!master)throw Error('Diese Funktion ist nur für Master verfügbar.');
let result={ok:true};
if(b.action==='resetAll'){if(b.confirmation!=='reset')throw Error('Bitte exakt reset eingeben.');const clean=initialState();clean.drinks=[];clean.events=[];clean.eventSync=null;clean.members=structuredClone(s.members);clean.roles=Object.fromEntries(s.members.map(p=>[p.userId,s.roles[p.userId]||'crew']));clean.roles[active]='master';writeState(clean);return reply({ok:true,reset:true})}
else if(b.action==='saveMember'){const name=str(b.name),email=str(b.email).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254)throw Error('Bitte eine gültige E-Mail-Adresse eingeben.');if(!['crew','admin','master'].includes(b.role))throw Error('Ungültige Rolle.');const memberId=b.id||b.authId||id;const existing=s.members.find(x=>x.userId===memberId);if(b.id&&!existing)throw Error('Mitglied nicht gefunden.');if(s.members.some(x=>x.userId!==memberId&&x.email.toLowerCase()===email))throw Error('Diese E-Mail-Adresse ist bereits vergeben.');if(s.roles[memberId]==='master'&&b.role!=='master'&&Object.values(s.roles).filter(r=>r==='master').length<=1)throw Error('Mindestens ein Master-Konto muss erhalten bleiben.');if(existing){existing.displayName=name;existing.email=email}else s.members.push({userId:memberId,displayName:name,email});s.roles[memberId]=b.role}
else if(b.action==='assignRole'){if(!s.members.some(p=>p.userId===b.user)||!['crew','admin','master'].includes(b.role))throw Error('Ungültige Rollenzuweisung.');if(s.roles[b.user]==='master'&&b.role!=='master'&&Object.values(s.roles).filter(r=>r==='master').length<=1)throw Error('Mindestens ein Master-Konto muss erhalten bleiben.');s.roles[b.user]=b.role}
else if(b.action==='receipt'){const record=s.records.find(x=>x.id===b.id&&x.kind==='receipt');if(!record)throw Error('Beleg nicht gefunden.');return reply({ok:true,record})}
else if(b.action==='allocate'){const amount=num(b.amount,100000000);if(amount<1)throw Error('Bitte einen positiven Betrag angeben.');const title=str(b.title);if(!s.records.some(x=>x.id===id)){const members=[...s.members].sort((a,b)=>a.userId.localeCompare(b.userId));const base=Math.floor(amount/members.length),rest=amount%members.length;const shares=members.map((p,i)=>({user:p.userId,name:p.displayName,amount:base+(i<rest?1:0)}));s.records.push({id,kind:'allocation',by:u.displayName,date:now,data:JSON.stringify({title,amount,shares})});for(const share of shares)if(share.amount>0)s.tallies.push({id:id+'-'+share.user,user:share.user,drink:null,kind:'allocation',allocation:id,name:'Umlage: '+title,price:share.amount,date:now,receipt:null})}}
else if(b.action==='syncEvents'){if(!Array.isArray(b.events)||!b.events.length||b.events.length>300)throw Error('Keine gültigen Termine gefunden.');s.events=mergeEvents(s.events,b.events);s.eventSync=now}
else if(b.action==='eventNote'){if(!s.events.some(x=>x.id===b.event))throw Error('Veranstaltung nicht gefunden.');if(typeof b.text!=='string'||!b.text.trim()||b.text.length>4000)throw Error('Bitte 1 bis 4.000 Zeichen eingeben.');if(!s.notes.some(x=>x.id===id))s.notes.push({id,event:b.event,user:active,name:u.displayName,text:b.text.trim(),date:now})}
else if(b.action==='applyEvent'){const event=s.events.find(x=>x.id===b.event);if(!event)throw Error('Veranstaltung nicht gefunden.');if(s.applications.some(x=>x.event===b.event&&x.user===active&&['pending','confirmed'].includes(x.status)))throw Error('Du bist für diese Veranstaltung bereits vorgemerkt.');if(!duties.includes(b.duty))throw Error('Bitte einen Dienst auswählen.');s.applications.push({id,event:b.event,user:active,name:u.displayName,status:'pending',duty:b.duty,note:String(b.note||'').slice(0,1000),date:now})}
else if(b.action==='decideApplication'){const row=s.applications.find(x=>x.id===b.id);if(!row)throw Error('Bewerbung nicht gefunden.');if(!['confirmed','rejected'].includes(b.status))throw Error('Ungültiger Status.');if(row.status!=='pending')throw Error('Diese Bewerbung wurde bereits bearbeitet.');if(b.status==='confirmed'){if(!duties.includes(b.duty))throw Error('Bitte einen Dienst auswählen.');row.duty=b.duty}row.status=b.status;row.decidedAt=now;row.decidedBy=u.displayName}
else if(b.action==='requestCorrection'){const dr=s.drinks.find(x=>x.id===b.drink);if(!dr)throw Error('Getränk nicht gefunden.');if(typeof b.text!=='string'||!b.text.trim()||b.text.length>2000)throw Error('Bitte eine Nachricht mit 1 bis 2.000 Zeichen eingeben.');if(!s.corrections.some(x=>x.id===id))s.corrections.push({id,user:active,name:u.displayName,drink:dr.id,drinkName:dr.name,text:b.text.trim(),date:now,status:'pending'})}
else if(b.action==='resolveCorrection'){const row=s.corrections.find(x=>x.id===b.id);if(!row||row.status!=='pending')throw Error('Anfrage bereits bearbeitet oder nicht gefunden.');const count=num(b.count,100000);const response=str(b.response);const open=s.tallies.filter(x=>x.user===row.user&&x.drink===row.drink&&!x.receipt&&!x.void);if(count>open.length)throw Error('Nicht genügend offene Striche. Bereits bezahlte Belege bleiben unverändert.');for(const t of open.slice().reverse().slice(0,count)){t.void=true;t.correction=row.id;t.voidAt=now;t.voidBy=u.displayName}Object.assign(row,{status:'resolved',count,response,handledAt:now,handledBy:u.displayName})}
else if(b.action==='shop'){if(!s.shopping.some(x=>x.id===id))s.shopping.unshift({id,name:str(b.name),by:u.displayName,date:now,done:0})}
else if(b.action==='done'){const row=s.shopping.find(x=>x.id===b.id);if(row)row.done=1}
else if(b.action==='drink'){const d={id:b.id||id,name:str(b.name),pack:num(b.pack,1000),price:num(b.price,100000),active:1};if(d.pack<1)throw Error('Mindestens eine Flasche pro Gebinde.');const i=s.drinks.findIndex(x=>x.id===d.id);if(i>=0)s.drinks[i]=d;else s.drinks.push(d)}
else if(b.action==='archiveDrink'){const d=s.drinks.find(x=>x.id===b.id);if(d)d.active=0}
else if(b.action==='tally'){const d=s.drinks.find(x=>x.id===b.drink&&x.active);if(!d)throw Error('Getränk nicht verfügbar.');if(!s.tallies.some(x=>x.id===id))s.tallies.push({id,user:active,drink:d.id,name:d.name,price:d.price,date:now,receipt:null})}
else if(b.action==='stock'||b.action==='order'){const ds=s.drinks.filter(x=>x.active);if(!ds.length)throw Error('Zuerst Getränke anlegen.');if(!Array.isArray(b.items))throw Error('Ungültige Mengen.');const items=ds.map(d=>{const row=b.items.find(x=>x.id===d.id);if(!row&&b.action==='stock')throw Error('Bitte alle Getränke erfassen.');return {id:d.id,name:d.name,pack:d.pack,cases:num(row?.cases??0),bottles:num(row?.bottles??0)}});if(b.action==='order'&&!items.some(x=>x.cases||x.bottles))throw Error('Bitte Bestellmengen eingeben.');const old=s.records.find(x=>x.id===id);const record=old||{id,kind:b.action,by:u.displayName,date:now,data:JSON.stringify(items)};if(!old)s.records.push(record);result.record=record}
else if(b.action==='settle'){if(!Array.isArray(b.ids)||!b.ids.length)throw Error('Keine offenen Positionen.');const items=s.tallies.filter(x=>x.user===b.user&&!x.receipt&&!x.void&&b.ids.includes(x.id));if(items.length!==b.ids.length)throw Error('Liste bereits abgeschlossen oder geändert.');const p=s.members.find(x=>x.userId===b.user);s.records.push({id,kind:'receipt',by:u.displayName,date:now,data:JSON.stringify({user:b.user,name:p?.displayName||b.user,items:items.map(x=>({...x}))})});for(const row of items)row.receipt=id}
else throw Error('Unbekannte Aktion.');writeState(s);return reply(result)
}catch(e){return reply({error:e instanceof Error?e.message:'Speichern fehlgeschlagen.'},400)}}
function reply(body,status=200){return {ok:status<400,status,json:async()=>body}}


const response=await apiFetch('/api/crew',command?{method:'POST',body:JSON.stringify(command)}:{});const body=await response.json();if(!response.ok)throw Error(body.error);return {state:output,body};
}
