import {csvInventory} from './inventory-csv-seed.mjs';
import {importInventory} from './inventory-import.mjs';
import {catalog,shoppingChoices,shoppingAction} from './shopping.mjs';
import {rentalView,infoView,community} from './community.mjs';
import {features,requireFeature} from './features.mjs';
import {management,balance,dutyPrices} from './management.mjs';
import {seedEvents,SOURCE_CHECKED,mergeEvents} from './event-seed.mjs';
import {operate,staffingView} from './operations-api.mjs';
export const duties=['Theke','Parkplatz','Ton','Licht','Eintritt','Joker'];
export function initialState(){return {members:[],roles:{},drinks:[],shopping:[],tallies:[],records:[],events:structuredClone(seedEvents),notes:[],corrections:[],applications:[],wall:[],eventSync:SOURCE_CHECKED}}
export async function run(state,active,command){
let output=structuredClone(state);
// Restore the verified next-show omitted by older homepage importers, once.
if(!output.nextShowRepairOct8){const existing=output.events.find(e=>e.day==='2026-10-10'&&(/cry.?sis/i.test(e.name.replace(/\s/g,''))||e.ticket==='https://rausgegangen.de/events/cry-sis-0/'));if(!existing)output.events.push({id:'bonanzbar-2026-10-10',day:'2026-10-10',name:'CRY SIS´',time:'19:00',description:'Coverrock',ticket:'https://rausgegangen.de/events/cry-sis-0/',source:'https://bonanzbar.jimdofree.com/'});else if(!existing.time)existing.time='19:00';output.nextShowRepairOct8=true;}
output.events.sort((a,b)=>a.day.localeCompare(b.day)||(a.time||'').localeCompare(b.time||'')||a.name.localeCompare(b.name));
// One catalog, preserving existing beverage IDs and order membership.
if(!output.inventoryUnified){for(const a of catalog(output)){const existing=output.drinks.find(d=>d.name.toLocaleLowerCase('de')===a.name.toLocaleLowerCase('de'));if(!existing)output.drinks.push({id:'supply-'+a.id,name:a.name,unit:a.unit,pack:1,price:0,guestPrice:0,purchasePrice:0,active:1,supply:true,showMenu:false,showTally:false,showShopping:a.active});}output.inventoryUnified=true;}
const readState=()=>output;const writeState=s=>{output=s};
if(output.members.find(x=>x.userId===active)?.disabled)throw Error('Dieses Konto wurde deaktiviert. Bitte Master kontaktieren.');
if(!output.members.some(x=>x.userId===active))throw Error('Kein Mitgliedskonto vorhanden.');
function num(v,max=100000){if(!Number.isSafeInteger(v)||v<0||v>max)throw Error('Bitte eine gültige ganze Anzahl eingeben.');return v}
function str(v){if(typeof v!=='string'||!v.trim()||v.length>300)throw Error('Bitte einen gültigen Text eingeben.');return v.trim()}
async function apiFetch(url,options={}){try{
if(url==='/api/events'){const s=readState();return reply({events:s.events,checked:s.eventSync})}
if(url!=='/api/crew')throw Error('Unbekannte Anfrage');const s=readState(),u=s.members.find(x=>x.userId===active),admin=['admin','master'].includes(s.roles[active]),master=s.roles[active]==='master',role=s.roles[active]||'crew',staff=['master','admin','crew'].includes(role),guest=role==='guest';
if(!options.method||options.method==='GET')return reply({user:u,role,staff,guest,admin,master,setup:false,features:features(s),rentals:rentalView(s,active,admin,guest),infos:infoView(s,role).map(i=>({...i,unread:s.infoRead?.[active]?.[i.id]!==i.updatedAt})),dutyPrices:master?dutyPrices(s):{},eventAccounts:master?s.eventAccounts||[]:[],accountEntries:(s.accountEntries||[]).filter(x=>master||x.user===active),accountBalance:balance(s,active),accountReceipts:master?s.records.filter(x=>x.kind==='accountReceipt').slice().reverse():[],staffing:staff&&features(s).staffing?staffingView(s):[],handovers:staff&&features(s).todos?s.handovers||[]:[],crewPeople:staff?s.members.filter(m=>['crew','admin','master'].includes(s.roles[m.userId])).map(m=>({id:m.userId,name:m.displayName})):[],recaps:(s.recaps||[]).filter(r=>admin||(features(s).recaps&&r.published)),ledgers:master?s.ledgers||[]:[],special:(admin||features(s).special)?s.special||null:null,wall:features(s).wall?s.wall||[]:[],corrections:(guest?[]:s.corrections).filter(x=>master||x.user===active),events:s.events,notes:staff?s.notes:[],applications:(staff&&(admin||features(s).staffing)?s.applications:[]).filter(x=>admin||x.user===active),eventSync:s.eventSync,drinks:s.drinks.filter(x=>x.active&&(admin||(guest?x.showMenu!==false:role==='member'?(x.showMenu!==false||x.showTally!==false):x.showTally!==false))).map(d=>guest?{id:d.id,name:d.name,guestPrice:d.guestPrice??null}:d).sort((a,b)=>a.name.localeCompare(b.name)),shoppingCatalog:admin?catalog(s):[],shoppingChoices:staff?shoppingChoices(s):[],shoppingHiddenDrinks:admin?s.shoppingHiddenDrinks||[]:[],shopping:(staff?s.shopping:[]).filter(x=>!x.done),stock:(admin?s.records:[]).filter(x=>x.kind==='stock').slice().reverse(),tallies:(guest?[]:s.tallies).filter(x=>!x.receipt&&!x.void&&(master||x.user===active)),people:admin?s.members.map(x=>({id:x.userId,name:x.displayName,email:x.email,disabled:!!x.disabled,role:s.roles[x.userId]||'crew'})):[],allocations:master?s.records.filter(x=>x.kind==='allocation').slice().reverse():[],receipts:master?s.records.filter(x=>x.kind==='receipt').slice().reverse():[],orders:admin?s.records.filter(x=>x.kind==='order').slice().reverse():[]});
const b=JSON.parse(options.body);requireFeature(s,b.action);if(guest&&!['readInfos','wallPost','wallComment','wallDelete','requestRental'].includes(b.action))throw Error('Gäste können nur Veranstaltungsinfos ansehen.');if(!staff&&!['readInfos','tally','undoTally','requestCorrection','wallPost','wallComment','wallDelete','requestRental'].includes(b.action))throw Error('Diese Funktion ist für Mitglieder nicht verfügbar.');const id=b.requestId||crypto.randomUUID(),now=new Date().toISOString();
if(['saveManualEvent','stock','saveBand','saveMember','saveSpecial','disableSpecial','eventVideo','drink','archiveDrink','order','done','syncEvents','decideApplication'].includes(b.action)&&!admin)throw Error('Bitte zum Admin-Konto wechseln.');
if(['settle','allocate','receipt','assignRole','resolveCorrection','resetAll'].includes(b.action)&&!master)throw Error('Diese Funktion ist nur für Master verfügbar.');
const shopResult=shoppingAction(s,b,{admin,staff,u,id,now});if(shopResult){writeState(s);return reply(shopResult)}
const extra=community(s,b,{active,admin,u,id,now});if(extra){writeState(s);return reply(extra)}
const managed=management(s,b,{active,admin,master,staff,u,id,now});if(managed){writeState(s);return reply(managed)}
const extension=operate(s,b,{active,admin,master,staff,u,id,now});if(extension){writeState(s);return reply(extension)}
let result={ok:true};
if(b.action==='resetInventoryCsv'){
if(!master)throw Error('Nur Master darf das Inventar ersetzen.');
if(s.inventoryCsvReset==='csv-2026-10-05-v1')throw Error('Diese CSV wurde bereits als neues Inventar eingerichtet.');
const matched=new Set(csvInventory.map(d=>d.name.toLocaleLowerCase('de')));
result=importInventory(s,{items:csvInventory,overwrite:true},true);
for(const d of s.drinks)if(!matched.has(d.name.toLocaleLowerCase('de')))d.active=0;
s.records.push({id,kind:'stock',by:u.displayName,date:now,data:JSON.stringify(s.drinks.filter(d=>d.active).map(d=>({id:d.id,name:d.name,pack:d.pack,purchasePrice:d.purchasePrice,cases:0,bottles:0,restMl:0,supply:!!d.supply}))),reason:'Neustart aus CSV – Bestand 0'});
s.inventoryCsvReset='csv-2026-10-05-v1';
}
else if(b.action==='importInventory'){result=importInventory(s,b,admin)}
else if(b.action==='resetAll'){if(b.confirmation!=='reset')throw Error('Bitte exakt reset eingeben.');const clean=initialState();clean.drinks=[];clean.events=[];clean.eventSync=null;clean.members=structuredClone(s.members);clean.roles=Object.fromEntries(s.members.map(p=>[p.userId,s.roles[p.userId]||'crew']));clean.roles[active]='master';writeState(clean);return reply({ok:true,reset:true})}
else if(b.action==='setMemberActive'){if(!admin)throw Error('Nur Admin oder Master.');const target=s.members.find(x=>x.userId===b.user);if(!target||typeof b.enabled!=='boolean')throw Error('Ungültiges Konto.');if(b.user===active)throw Error('Das eigene Konto kann nicht deaktiviert werden.');if(s.roles[b.user]==='master')throw Error('Master-Konten können hier nicht deaktiviert werden.');if(s.roles[b.user]==='admin'&&!master)throw Error('Nur Master darf Admin-Konten deaktivieren.');target.disabled=!b.enabled;target.statusChangedAt=now;target.statusChangedBy=active;}
else if(b.action==='saveMember'){if(!master){const existing=s.members.find(x=>x.userId===b.id);if(existing&&b.role!==s.roles[existing.userId])throw Error('Nur Master darf Rollen ändern.');if(!existing&&b.role!=='crew')throw Error('Admin kann neue Konten als Crew anlegen; Rollen vergibt Master.');}const name=str(b.name),email=str(b.email).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254)throw Error('Bitte eine gültige E-Mail-Adresse eingeben.');if(!['crew','admin','master','member','guest'].includes(b.role))throw Error('Ungültige Rolle.');const memberId=b.id||b.authId||id;if(memberId===active&&s.roles[active]==='master'&&b.role!=='master')throw Error('Du kannst deine eigene Master-Rolle nicht herabsetzen.');const existing=s.members.find(x=>x.userId===memberId);if(b.id&&!existing)throw Error('Mitglied nicht gefunden.');if(s.members.some(x=>x.userId!==memberId&&x.email.toLowerCase()===email))throw Error('Diese E-Mail-Adresse ist bereits vergeben.');if(s.roles[memberId]==='master'&&b.role!=='master'&&Object.values(s.roles).filter(r=>r==='master').length<=1)throw Error('Mindestens ein Master-Konto muss erhalten bleiben.');if(existing){existing.displayName=name;existing.email=email}else s.members.push({userId:memberId,displayName:name,email});s.roles[memberId]=b.role}
else if(b.action==='assignRole'){if(b.user===active&&master&&b.role!=='master')throw Error('Du kannst deine eigene Master-Rolle nicht herabsetzen.');if(!s.members.some(p=>p.userId===b.user)||!['crew','admin','master','member','guest'].includes(b.role))throw Error('Ungültige Rollenzuweisung.');if(s.roles[b.user]==='master'&&b.role!=='master'&&Object.values(s.roles).filter(r=>r==='master').length<=1)throw Error('Mindestens ein Master-Konto muss erhalten bleiben.');s.roles[b.user]=b.role}
else if(b.action==='receipt'){const record=s.records.find(x=>x.id===b.id&&x.kind==='receipt');if(!record)throw Error('Beleg nicht gefunden.');return reply({ok:true,record})}
else if(b.action==='allocate'){const amount=num(b.amount,100000000);if(amount<1)throw Error('Bitte einen positiven Betrag angeben.');const title=str(b.title);if(!s.records.some(x=>x.id===id)){const members=s.members.filter(p=>['crew','admin','master'].includes(s.roles[p.userId])).sort((a,b)=>a.userId.localeCompare(b.userId));if(!members.length)throw Error('Keine Konten für die Umlage vorhanden.');const base=Math.floor(amount/members.length),rest=amount%members.length;const shares=members.map((p,i)=>({user:p.userId,name:p.displayName,amount:base+(i<rest?1:0)}));s.records.push({id,kind:'allocation',by:u.displayName,date:now,data:JSON.stringify({title,amount,shares})});for(const share of shares)if(share.amount>0)s.tallies.push({id:id+'-'+share.user,user:share.user,drink:null,kind:'allocation',allocation:id,name:'Umlage: '+title,price:share.amount,date:now,receipt:null})}}
else if(b.action==='syncEvents'){if(!Array.isArray(b.events)||!b.events.length||b.events.length>300)throw Error('Keine gültigen Termine gefunden.');s.events=mergeEvents(s.events,b.events).map(e=>({...e,youtube:s.events.find(old=>old.id===e.id)?.youtube||''}));s.eventSync=now}
else if(b.action==='wallPost'){const text=String(b.text||'').trim(),image=b.image||'';if(text.length>2000||(!text&&!image))throw Error('Bitte ein Bild oder einen Text hinzufügen.');if(image&&(!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(image)||image.length>400000))throw Error('Bildformat oder Bildgröße nicht erlaubt.');s.wall??=[];if(!s.wall.some(x=>x.id===id))s.wall.unshift({id,user:active,name:u.displayName,text,image,date:now,comments:[]})}
else if(b.action==='wallComment'){const post=(s.wall||[]).find(x=>x.id===b.post);if(!post)throw Error('Beitrag nicht gefunden.');const text=String(b.text||'').trim();if(!text||text.length>1000)throw Error('Bitte 1 bis 1.000 Zeichen eingeben.');if(!post.comments.some(x=>x.id===id))post.comments.push({id,user:active,name:u.displayName,text,date:now})}
else if(b.action==='wallDelete'){const post=(s.wall||[]).find(x=>x.id===b.post);if(!post)throw Error('Beitrag nicht gefunden.');const target=b.comment?post.comments.find(x=>x.id===b.comment):post;if(!target)throw Error('Kommentar nicht gefunden.');if(!admin&&target.user!==active)throw Error('Nur eigene Beiträge dürfen gelöscht werden.');if(b.comment)post.comments=post.comments.filter(x=>x.id!==b.comment);else s.wall=s.wall.filter(x=>x.id!==b.post)}
else if(b.action==='saveManualEvent'){const name=str(b.name),day=String(b.day||''),time=String(b.time||''),ticket=String(b.ticket||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||!Number.isFinite(Date.parse(day))||new Date(day+'T12:00:00Z').toISOString().slice(0,10)!==day)throw Error('Bitte gültiges Datum angeben.');if(time&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(time))throw Error('Bitte gültige Uhrzeit angeben.');if(ticket){let url;try{url=new URL(ticket)}catch{throw Error('Ticketlink ungültig.')}if(!['https:','http:'].includes(url.protocol)||url.username||url.password)throw Error('Ticketlink ungültig.');}const eventId=b.id||'manual-'+id;const prior=s.events.find(e=>e.id===eventId);if(b.id&&!prior)throw Error('Veranstaltung nicht gefunden.');if(prior)Object.assign(prior,{name,day,time,ticket});else s.events.push({id:eventId,name,day,time,ticket,manual:true,bandImages:[],bandInfo:''});s.events.sort((a,b)=>a.day.localeCompare(b.day)||(a.time||'').localeCompare(b.time||'')||a.name.localeCompare(b.name));result.eventId=eventId;}
else if(b.action==='saveBand'){const e=s.events.find(e=>e.id===b.event);if(!e)throw Error('Veranstaltung nicht gefunden.');if(typeof b.info!=='string'||b.info.length>5000)throw Error('Bandinfos dürfen maximal 5.000 Zeichen enthalten.');let homepage=String(b.homepage||'').trim();if(homepage){let url;try{url=new URL(homepage)}catch{throw Error('Bitte eine vollständige Homepage-Adresse eingeben.')}if(!['https:','http:'].includes(url.protocol)||url.username||url.password)throw Error('Bitte einen HTTP- oder HTTPS-Link verwenden.');homepage=url.href}if(!Array.isArray(b.images)||b.images.length>4)throw Error('Maximal vier Bandbilder.');for(const image of b.images)if(typeof image!=='string'||image.length>400000||!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(image))throw Error('Ungültiges Bandbild.');let youtube=String(b.youtube??e.youtube??'').trim();if(youtube){let url;try{url=new URL(youtube)}catch{throw Error('Bitte einen gültigen YouTube-Link eingeben.')}if(url.protocol!=='https:'||!['youtube.com','www.youtube.com','m.youtube.com','youtu.be'].includes(url.hostname)||url.username||url.password)throw Error('Bitte einen HTTPS-Link von YouTube verwenden.');youtube=url.href}Object.assign(e,{bandInfo:b.info.trim(),bandHomepage:homepage,bandImages:b.images,youtube})}
else if(b.action==='saveSpecial'){const title=str(b.title);if(title.length>80)throw Error('Titel maximal 80 Zeichen.');const description=String(b.description||'').trim();if(description.length>300)throw Error('Beschreibung maximal 300 Zeichen.');if(!/^\d{4}-\d{2}-\d{2}$/.test(b.day)||new Date(b.day+'T12:00:00Z').toISOString().slice(0,10)!==b.day)throw Error('Bitte ein gültiges Datum wählen.');s.special={title,description,price:num(b.price,100000),day:b.day,active:true}}
else if(b.action==='disableSpecial'){if(s.special)s.special.active=false}
else if(b.action==='eventVideo'){const event=s.events.find(x=>x.id===b.event);if(!event)throw Error('Veranstaltung nicht gefunden.');const value=String(b.youtube||'').trim();if(value){let url;try{url=new URL(value)}catch{throw Error('Bitte einen gültigen YouTube-Link eingeben.')}if(url.protocol!=='https:'||!['youtube.com','www.youtube.com','m.youtube.com','youtu.be'].includes(url.hostname)||url.username||url.password)throw Error('Bitte einen HTTPS-Link von YouTube verwenden.');event.youtube=url.href}else event.youtube=''}
else if(b.action==='eventNote'){if(!s.events.some(x=>x.id===b.event))throw Error('Veranstaltung nicht gefunden.');if(typeof b.text!=='string'||!b.text.trim()||b.text.length>4000)throw Error('Bitte 1 bis 4.000 Zeichen eingeben.');if(!s.notes.some(x=>x.id===id))s.notes.push({id,event:b.event,user:active,name:u.displayName,text:b.text.trim(),date:now})}
else if(b.action==='assignService'){
if(!master)throw Error('Nur Master darf Dienste manuell eintragen.');
const person=s.members.find(p=>p.userId===b.user&&!p.disabled);
if(!person||!['crew','admin'].includes(s.roles[b.user]))throw Error('Bitte ein aktives Crew- oder Admin-Konto wählen.');
if(!s.events.some(e=>e.id===b.event)||!duties.includes(b.duty))throw Error('Veranstaltung oder Dienst ungültig.');
if(s.applications.some(a=>a.user===b.user&&a.event===b.event&&a.status==='confirmed'))throw Error('Diese Person ist bereits für die Veranstaltung eingetragen.');
const pending=s.applications.find(a=>a.user===b.user&&a.event===b.event&&a.status==='pending');
if(pending)Object.assign(pending,{status:'confirmed',duty:b.duty,decidedAt:now,decidedBy:u.displayName,manual:true});
else s.applications.push({id,event:b.event,user:b.user,name:person.displayName,status:'confirmed',duty:b.duty,note:'Manuell durch Master eingetragen',date:now,decidedAt:now,decidedBy:u.displayName,manual:true});
}
else if(b.action==='applyEvent'){const event=s.events.find(x=>x.id===b.event);if(!event)throw Error('Veranstaltung nicht gefunden.');if(s.applications.some(x=>x.event===b.event&&x.user===active&&['pending','confirmed'].includes(x.status)))throw Error('Du bist für diese Veranstaltung bereits vorgemerkt.');if(!duties.includes(b.duty))throw Error('Bitte einen Dienst auswählen.');s.applications.push({id,event:b.event,user:active,name:u.displayName,status:'pending',duty:b.duty,note:String(b.note||'').slice(0,1000),date:now})}
else if(b.action==='decideApplication'){const row=s.applications.find(x=>x.id===b.id);if(!row)throw Error('Bewerbung nicht gefunden.');if(!['confirmed','rejected'].includes(b.status))throw Error('Ungültiger Status.');if(row.status!=='pending')throw Error('Diese Bewerbung wurde bereits bearbeitet.');if(b.status==='confirmed'){if(!duties.includes(b.duty))throw Error('Bitte einen Dienst auswählen.');row.duty=b.duty}row.status=b.status;row.decidedAt=now;row.decidedBy=u.displayName}
else if(b.action==='requestCorrection'){const dr=s.drinks.find(x=>x.id===b.drink);if(!dr)throw Error('Getränk nicht gefunden.');if(typeof b.text!=='string'||!b.text.trim()||b.text.length>2000)throw Error('Bitte eine Nachricht mit 1 bis 2.000 Zeichen eingeben.');if(!s.corrections.some(x=>x.id===id))s.corrections.push({id,user:active,name:u.displayName,drink:dr.id,drinkName:dr.name,text:b.text.trim(),date:now,status:'pending'})}
else if(b.action==='resolveCorrection'){const row=s.corrections.find(x=>x.id===b.id);if(!row||row.status!=='pending')throw Error('Anfrage bereits bearbeitet oder nicht gefunden.');const count=num(b.count,100000);const response=str(b.response);const open=s.tallies.filter(x=>x.user===row.user&&x.drink===row.drink&&!x.receipt&&!x.void);if(count>open.length)throw Error('Nicht genügend offene Striche. Bereits bezahlte Belege bleiben unverändert.');for(const t of open.slice().reverse().slice(0,count)){t.void=true;t.correction=row.id;t.voidAt=now;t.voidBy=u.displayName}Object.assign(row,{status:'resolved',count,response,handledAt:now,handledBy:u.displayName})}
else if(b.action==='done'){const row=s.shopping.find(x=>x.id===b.id);if(row)row.done=1}
else if(b.action==='drink'){const prior=s.drinks.find(x=>x.id===b.id);for(const k of ['showMenu','showTally','showShopping','partialBottle','supply'])if(b[k]!=null&&typeof b[k]!=='boolean')throw Error('Ungültige Auswahl.');const d={...prior,showMenu:b.showMenu??prior?.showMenu??true,showTally:b.showTally??prior?.showTally??true,showShopping:b.showShopping??prior?.showShopping??!(s.shoppingHiddenDrinks||[]).includes(b.id),partialBottle:b.partialBottle??prior?.partialBottle??false,supply:b.supply??prior?.supply??false,unit:b.unit??prior?.unit??'Flasche',id:b.id||id,name:str(b.name),pack:num(b.pack,1000),price:num(b.price,100000),purchasePrice:b.purchasePrice==null?(s.drinks.find(x=>x.id===b.id)?.purchasePrice??0):num(b.purchasePrice,100000),guestPrice:b.guestPrice==null?(s.drinks.find(x=>x.id===b.id)?.guestPrice??null):num(b.guestPrice,100000),active:1};if(d.pack<1)throw Error('Mindestens eine Flasche pro Gebinde.');const i=s.drinks.findIndex(x=>x.id===d.id);if(i>=0)s.drinks[i]=d;else s.drinks.push(d)}
else if(b.action==='archiveDrink'){const d=s.drinks.find(x=>x.id===b.id);if(d)d.active=0}
else if(b.action==='tally'){result.tallyId=id;const d=s.drinks.find(x=>x.id===b.drink&&x.active&&x.showTally!==false);if(!d)throw Error('Getränk nicht verfügbar.');if(!s.tallies.some(x=>x.id===id))s.tallies.push({id,user:active,drink:d.id,name:d.name,price:d.price,date:now,receipt:null})}
else if(b.action==='stock'||b.action==='order'){const ds=s.drinks.filter(x=>x.active&&(b.action==='stock'||!x.supply));if(!ds.length)throw Error('Zuerst Getränke anlegen.');if(!Array.isArray(b.items))throw Error('Ungültige Mengen.');const items=ds.map(d=>{const row=b.items.find(x=>x.id===d.id);if(!row&&!d.supply&&b.action==='stock')throw Error('Bitte alle Getränke erfassen.');const rest=b.action==='stock'?num(row?.restMl??0,700):0;if(rest&&!d.partialBottle)throw Error('Restmenge nur bei aktivierter 0,7-l-Flasche.');return {id:d.id,name:d.name,pack:d.pack,purchasePrice:d.purchasePrice??null,cases:num(row?.cases??0),bottles:num(row?.bottles??0),...(b.action==='stock'?{restMl:rest,supply:!!d.supply}: {})}});if(b.action==='order'&&!items.some(x=>x.cases||x.bottles))throw Error('Bitte Bestellmengen eingeben.');const old=s.records.find(x=>x.id===id);const record=old||{id,kind:b.action,by:u.displayName,date:now,data:JSON.stringify(items)};if(!old)s.records.push(record);result.record=record}
else if(b.action==='settle'){if(!Array.isArray(b.ids)||!b.ids.length)throw Error('Keine offenen Positionen.');const items=s.tallies.filter(x=>x.user===b.user&&!x.receipt&&!x.void&&b.ids.includes(x.id));if(items.length!==b.ids.length)throw Error('Liste bereits abgeschlossen oder geändert.');const p=s.members.find(x=>x.userId===b.user);s.records.push({id,kind:'receipt',by:u.displayName,date:now,data:JSON.stringify({user:b.user,name:p?.displayName||b.user,items:items.map(x=>({...x}))})});for(const row of items)row.receipt=id}
else throw Error('Unbekannte Aktion.');writeState(s);return reply(result)
}catch(e){return reply({error:e instanceof Error?e.message:'Daten konnten nicht gespeichert werden.'},400)}}
function reply(body,status=200){return {ok:status<400,status,json:async()=>body}}


const response=await apiFetch('/api/crew',command?{method:'POST',body:JSON.stringify(command)}:{});const body=await response.json();if(!response.ok)throw Error(body.error);return {state:output,body};
}
