export const dayNow=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Berlin'}).format(new Date());
const duties=['Theke','Parkplatz','Ton','Licht','Eintritt','Joker'];
const count=(x,max=100000000)=>{if(!Number.isSafeInteger(x)||x<0||x>max)throw Error('Bitte eine gültige ganze Zahl eingeben.');return x};
const text=(v,max)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw Error('Bitte einen gültigen Text eingeben.');return v.trim()};
export function staffingView(s){return s.events.map(e=>({event:e.id,configured:!!s.staffing?.[e.id],duties:duties.map(d=>({duty:d,needed:s.staffing?.[e.id]?.[d]??0,confirmed:s.applications.filter(a=>a.event===e.id&&a.duty===d&&a.status==='confirmed').length}))}))}
export function operate(s,b,{active,admin,master,staff,u,id,now}){
const names=['saveStaffing','handoverAdd','handoverStatus','saveRecap','deleteRecap','ledgerAdd','ledgerDelete','ledgerClose','undoTally'];if(!names.includes(b.action))return null;
if(['saveStaffing','saveRecap','deleteRecap'].includes(b.action)&&!admin)throw Error('Nur Admin oder Master.');
if(b.action.startsWith('ledger')&&!master)throw Error('Veranstaltungsabrechnung ist nur für Master verfügbar.');
if(b.action.startsWith('handover')&&!staff)throw Error('Das Übergabebuch ist nur für die Crew.');
const event=()=>{const e=s.events.find(e=>e.id===b.event);if(!e)throw Error('Veranstaltung nicht gefunden.');return e};
if(b.action==='saveStaffing'){event();if(!b.needs||typeof b.needs!=='object')throw Error('Bedarf fehlt.');const needs={};for(const d of duties)needs[d]=count(b.needs[d],100);s.staffing??={};s.staffing[b.event]=needs}
if(b.action==='handoverAdd'){s.handovers??=[];const message=text(b.text,2000);if(b.assignee&&!s.members.some(m=>m.userId===b.assignee&&['crew','admin','master'].includes(s.roles[m.userId])))throw Error('Bitte ein Crew-Mitglied wählen.');if(!s.handovers.some(r=>r.id===id))s.handovers.unshift({id,text:message,assignee:b.assignee||'',priority:b.priority==='urgent'?'urgent':'normal',status:'open',by:u.displayName,user:active,date:now})}
if(b.action==='handoverStatus'){const row=(s.handovers||[]).find(r=>r.id===b.id);if(!row)throw Error('Eintrag nicht gefunden.');if(!['open','progress','done'].includes(b.status))throw Error('Ungültiger Status.');Object.assign(row,{status:b.status,changedAt:now,changedBy:u.displayName})}
if(b.action==='saveRecap'){const e=event();if(e.day>=dayNow())throw Error('Rückblicke sind erst nach dem Veranstaltungstag möglich.');const title=text(b.title,100),description=text(b.text,3000);if(!Array.isArray(b.images)||b.images.length>6)throw Error('Maximal sechs Fotos.');for(const image of b.images)if(typeof image!=='string'||image.length>400000||!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(image))throw Error('Ungültiges Foto.');if(b.published&&b.images.length&&!b.consent)throw Error('Bitte die Freigabe der Fotos bestätigen.');s.recaps??=[];const prior=s.recaps.find(r=>r.event===b.event);const recap={id:prior?.id||id,event:b.event,title,text:description,images:b.images,published:b.published===true,date:now,by:u.displayName};if(prior)Object.assign(prior,recap);else s.recaps.unshift(recap)}
if(b.action==='deleteRecap')s.recaps=(s.recaps||[]).filter(r=>r.id!==b.id);
if(b.action.startsWith('ledger')){event();s.ledgers??=[];let ledger=s.ledgers.find(l=>l.event===b.event);if(ledger?.closed)throw Error('Diese Abrechnung ist bereits abgeschlossen.');if(!ledger){ledger={event:b.event,rows:[],closed:false};s.ledgers.push(ledger)}if(b.action==='ledgerAdd'){if(!['income','expense'].includes(b.kind))throw Error('Bitte Einnahme oder Ausgabe auswählen.');const label=text(b.label,150),amount=count(b.amount);if(!amount)throw Error('Betrag muss größer als null sein.');if(!ledger.rows.some(r=>r.id===id))ledger.rows.push({id,label,amount,kind:b.kind,date:now,by:u.displayName})}if(b.action==='ledgerDelete')ledger.rows=ledger.rows.filter(r=>r.id!==b.id);if(b.action==='ledgerClose'){if(!ledger.rows.length)throw Error('Keine Positionen vorhanden.');ledger.closed=true;ledger.closedAt=now;ledger.closedBy=u.displayName}}
if(b.action==='undoTally'){const t=s.tallies.find(t=>t.id===b.id);if(!t||t.user!==active||!t.drink||t.receipt||t.void||Date.parse(now)-Date.parse(t.date)>10000)throw Error('Rückgängig nicht mehr möglich. Bitte Korrektur an Master senden.');Object.assign(t,{void:true,voidAt:now,voidBy:u.displayName,reason:'Sofortkorrektur'})}
return {ok:true};
}
