import {createHash} from 'node:crypto';
export function config(){const {SUPABASE_URL:url,SUPABASE_SERVICE_ROLE_KEY:key,APP_ORIGIN:origin}=process.env;if(!url||!key||!origin)throw Error('Server noch nicht eingerichtet.');return {url,key,origin:new URL(origin).origin}}
export async function sb(path,options={}){const {url,key}=config();const r=await fetch(url+path,{...options,headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(15000)});const t=await r.text();let data;try{data=t?JSON.parse(t):null}catch{data=null}if(!r.ok){const messages={email_not_confirmed:'Bitte zuerst deine E-Mail bestätigen. Du kannst die Bestätigungs-Mail erneut anfordern.',invalid_credentials:'E-Mail-Adresse oder Passwort stimmt nicht.',otp_expired:'Dieser Link ist abgelaufen oder wurde bereits benutzt. Bitte einen neuen Link anfordern.',over_email_send_rate_limit:'Zu viele E-Mail-Anfragen. Bitte später erneut versuchen.',email_address_not_authorized:'Der E-Mail-Versand ist noch eingeschränkt. Bitte die technische Betreuung wegen SMTP kontaktieren.',unexpected_failure:'Der Anmeldedienst konnte die Anfrage nicht ausführen. Bitte die technische Betreuung informieren.'};const e=Error(messages[data?.code]||(path.startsWith('/auth/v1/')?'Anmeldung oder E-Mail-Versand fehlgeschlagen. Bitte erneut versuchen; falls keine E-Mail ankommt, die technische Betreuung informieren.':'Anfrage an Datenbank oder Anmeldung fehlgeschlagen.'));e.status=r.status;throw e}return data}
export async function read(){const rows=await sb('/rest/v1/app_state?id=eq.1&select=revision,state');if(!rows?.length)throw Error('Datenbank zuerst initialisieren.');return rows[0]}
export async function commit(revision,state){return await sb('/rest/v1/rpc/commit_state',{method:'POST',body:JSON.stringify({expected:revision,next_state:state})})}
export function json(res,status,data){res.setHeader('Cache-Control','no-store');res.status(status).json(data)}
export function body(req){const b=typeof req.body==='string'?JSON.parse(req.body):req.body;if(!b||typeof b!=='object'||Array.isArray(b)||Buffer.byteLength(JSON.stringify(b),'utf8')>3000000)throw Error('Ungültige Anfrage.');return b}
export function origin(req){if(req.headers.origin!==config().origin){const e=Error('Anfrage nicht erlaubt.');e.status=403;throw e}}
const access='__Host-bb_access',refresh='__Host-bb_refresh';
export function cookies(res,session){res.setHeader('Set-Cookie',[`${access}=${session?.access_token||''}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${session?3600:0}`,`${refresh}=${session?.refresh_token||''}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${session?2592000:0}`])}
export async function user(req,res){const c=Object.fromEntries((req.headers.cookie||'').split(';').filter(x=>x.includes('=')).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),x.slice(i+1)]}));let token=c[access];try{if(!token)throw Error();const result=await sb('/auth/v1/user',{headers:{Authorization:'Bearer '+token}});req.authToken=token;return result}catch{if(c[refresh])try{const s=await sb('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:c[refresh]})});cookies(res,s);req.authToken=s.access_token;return s.user}catch{}}const e=Error('Bitte anmelden.');e.status=401;throw e}
export async function limit(req,scope,value='',max=10){const ip=req.headers['x-vercel-forwarded-for']||req.headers['x-forwarded-for']||'unknown';const key=createHash('sha256').update(scope+':'+ip+':'+value).digest('hex');const ok=await sb('/rest/v1/rpc/check_rate',{method:'POST',body:JSON.stringify({bucket:key,maximum:max})});if(!ok){const e=Error('Zu viele Versuche. Bitte in 15 Minuten erneut versuchen.');e.status=429;throw e}}
export function failure(res,e){json(res,e.status&&[401,403,429].includes(e.status)?e.status:400,{error:e.message||'Anfrage fehlgeschlagen.'})}
