import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import Crew from './crew';
import PublicEvents from './public-events';
async function auth(action:string,args:any={}){const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...args})});const x=await r.json();if(!r.ok)throw Error(x.error||'Anmeldung fehlgeschlagen.');return x}
function App(){const [member,setMember]=useState<any>(null),[showLogin,setShowLogin]=useState(false),[loading,setLoading]=useState(true),[splash,setSplash]=useState(()=>{try{return sessionStorage.getItem('bonanzbar-welcome-seen')!=='1'}catch{return true}}),[name,setName]=useState(''),[verificationType,setVerificationType]=useState('recovery'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[mode,setMode]=useState('login'),[token,setToken]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
async function load(){try{const r=await fetch('/api/auth');if(r.ok)setMember((await r.json()).member);else setMember(null)}catch{setMessage('Server nicht erreichbar. Bitte erneut versuchen.')}finally{setLoading(false)}}
useEffect(()=>{try{sessionStorage.setItem('bonanzbar-welcome-seen','1')}catch{}const q=new URLSearchParams(location.search);if(q.has('token_hash')){setVerificationType(q.get('type')||'recovery');setShowLogin(true);setToken(q.get('token_hash')||'');setMode('verify');history.replaceState(null,'',location.pathname);setLoading(false)}else load();const timer=setTimeout(()=>setSplash(false),2500);const logout=()=>setMember(null);window.addEventListener('signed-out',logout);return()=>{clearTimeout(timer);window.removeEventListener('signed-out',logout)}},[]);
async function submit(e:any){e.preventDefault();setMessage('');setBusy(true);try{if(mode==='verify'){await auth('verify',{token,type:verificationType});setToken('');if(verificationType==='recovery')setMode('password');else{setMode('login');await load()}}else if(mode==='password'){if(password!==repeat)throw Error('Die Passwörter stimmen nicht überein.');await auth('password',{password});setPassword('');setRepeat('');setMode('login');await load()}else if(mode==='signup'){if(password!==repeat)throw Error('Die Passwörter stimmen nicht überein.');await auth('signup',{name,email,password});setPassword('');setRepeat('');setMode('login');setMessage('Bitte bestätige deine E-Mail über den zugesandten Link. Danach startet dein Konto als Gast.')}else if(mode==='recover'){await auth('recover',{email});setMessage('Wenn dein Konto angelegt ist, erhältst du einen Link per E-Mail. Bitte auch im Spamordner nachsehen.')}else{await auth('login',{email,password});setPassword('');await load()}}catch(err){setMessage((err as Error).message)}finally{setBusy(false)}}
if(splash)return <div className="welcome-screen"><img src="/skull.png" alt="Bonanzbar Totenkopf"/><h1>WELCOME<br/><small>IN DER BONANZBAR</small></h1></div>;
if(loading)return <main className="auth-box">Anmeldung wird geprüft …</main>;
if(member&&mode==='login')return <><div className="session-bar"><span>{member.displayName}</span><button onClick={async()=>{try{await auth('logout');setMember(null)}catch{setMessage('Abmelden fehlgeschlagen.')}}}>Abmelden</button>{message&&<span role="status">{message}</span>}</div><Crew/></>;
if(!showLogin&&mode==='login')return <PublicEvents onLogin={()=>{setShowLogin(true);setMessage('')}}/>;
return <main className="auth-box"><button className="auth-secondary" onClick={()=>{setShowLogin(false);setMode('login');setPassword('');setRepeat('');setMessage('')}}>← Veranstaltungen ansehen</button><img className="auth-logo" src="/logo.jpg" alt="Bonanzbar"/><h1>{mode==='password'?'Dein Passwort':mode==='verify'?'E-Mail-Link bestätigen':mode==='recover'?'Passwort festlegen / vergessen':mode==='signup'?'Dein Bonanzbar-Konto':'Willkommen in der Bonanzbar'}</h1><form onSubmit={submit}>{mode==='signup'&&<label>Benutzername<input required maxLength={80} autoComplete="nickname" value={name} onChange={e=>setName(e.target.value)}/></label>}{['login','recover','signup'].includes(mode)&&<label>E-Mail-Adresse<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}{['login','password','signup'].includes(mode)&&<label>Passwort<input type="password" required minLength={mode==='login'?1:12} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>}{['password','signup'].includes(mode)&&<label>Passwort wiederholen<input type="password" minLength={12} required autoComplete="new-password" value={repeat} onChange={e=>setRepeat(e.target.value)}/></label>}<button disabled={busy}>{busy?'Bitte warten …':mode==='verify'?'Link bestätigen':mode==='recover'?'Passwort-Link senden':mode==='password'?'Passwort speichern':mode==='signup'?'Registrieren':'Anmelden'}</button></form><p role="status">{message}</p>{mode!=='password'&&<button className="auth-secondary" onClick={()=>{setMode(mode==='login'?'recover':'login');setMessage('')}}>{mode==='login'?'Passwort festlegen / vergessen':'Zur Anmeldung'}</button>}{mode==='login'&&<><button className="auth-secondary" onClick={()=>{setMode('signup');setMessage('');setPassword('')}}>Neues Konto registrieren</button><button className="auth-secondary" disabled={busy||!email} onClick={async()=>{setBusy(true);try{await auth('resend',{email});setMessage('Falls eine Bestätigung aussteht, erhältst du eine neue E-Mail.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}>Bestätigungs-Mail erneut senden</button></>}<p>Neue Konten starten nach E-Mail-Bestätigung als Gast. Weitere Bereiche gibt der Master frei. Du meldest dich mit deiner E-Mail-Adresse an.</p><details><summary>Auf dem Homebildschirm installieren</summary><p>iPhone: In Safari öffnen → Teilen → Zum Home-Bildschirm. Android: Im Browsermenü „App installieren“ oder „Zum Startbildschirm hinzufügen“ wählen. Die App benötigt eine Internetverbindung.</p></details></main>}
createRoot(document.getElementById('root')!).render(<App/>);
