import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import Crew from './crew';
async function auth(action:string,args:any={}){const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...args})});const x=await r.json();if(!r.ok)throw Error(x.error||'Anmeldung fehlgeschlagen.');return x}
function App(){const [member,setMember]=useState<any>(null),[loading,setLoading]=useState(true),[splash,setSplash]=useState(true),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[mode,setMode]=useState('login'),[token,setToken]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
async function load(){try{const r=await fetch('/api/auth');if(r.ok)setMember((await r.json()).member);else setMember(null)}catch{setMessage('Server nicht erreichbar. Bitte erneut versuchen.')}finally{setLoading(false)}}
useEffect(()=>{const q=new URLSearchParams(location.search);if(q.has('token_hash')){setToken(q.get('token_hash')||'');setMode('verify');history.replaceState(null,'',location.pathname);setLoading(false)}else load();const timer=setTimeout(()=>setSplash(false),2500);const logout=()=>setMember(null);window.addEventListener('signed-out',logout);return()=>{clearTimeout(timer);window.removeEventListener('signed-out',logout)}},[]);
async function submit(e:any){e.preventDefault();setMessage('');setBusy(true);try{if(mode==='verify'){await auth('verify',{token});setToken('');setMode('password')}else if(mode==='password'){if(password!==repeat)throw Error('Die Passwörter stimmen nicht überein.');await auth('password',{password});setPassword('');setRepeat('');setMode('login');await load()}else if(mode==='recover'){await auth('recover',{email});setMessage('Wenn dein Konto angelegt ist, erhältst du einen Link per E-Mail. Bitte auch im Spamordner nachsehen.')}else{await auth('login',{email,password});setPassword('');await load()}}catch(err){setMessage((err as Error).message)}finally{setBusy(false)}}
if(splash)return <div className="welcome-screen"><img src="/skull.png" alt="Bonanzbar Totenkopf"/><h1>WELCOME<br/><small>IN DER BONANZBAR</small></h1></div>;
if(loading)return <main className="auth-box">Anmeldung wird geprüft …</main>;
if(member&&mode==='login')return <><div className="session-bar"><span>{member.displayName}</span><button onClick={async()=>{try{await auth('logout');setMember(null)}catch{setMessage('Abmelden fehlgeschlagen.')}}}>Abmelden</button>{message&&<span role="status">{message}</span>}</div><Crew/></>;
return <main className="auth-box"><img className="auth-logo" src="/logo.jpg" alt="Bonanzbar"/><h1>{mode==='password'?'Dein Passwort':mode==='verify'?'E-Mail-Link bestätigen':mode==='recover'?'Passwort festlegen / vergessen':'Willkommen, Crew!'}</h1><form onSubmit={submit}>{['login','recover'].includes(mode)&&<label>E-Mail-Adresse<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}{['login','password'].includes(mode)&&<label>Passwort<input type="password" required minLength={mode==='password'?12:1} maxLength={128} autoComplete={mode==='password'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>}{mode==='password'&&<label>Passwort wiederholen<input type="password" minLength={12} required autoComplete="new-password" value={repeat} onChange={e=>setRepeat(e.target.value)}/></label>}<button disabled={busy}>{busy?'Bitte warten …':mode==='verify'?'Link bestätigen':mode==='recover'?'Passwort-Link senden':mode==='password'?'Passwort speichern':'Anmelden'}</button></form><p role="status">{message}</p>{mode!=='password'&&<button className="auth-secondary" onClick={()=>{setMode(mode==='login'?'recover':'login');setMessage('')}}>{mode==='login'?'Passwort festlegen / vergessen':'Zur Anmeldung'}</button>}<p>Nur für angelegte Mitglieder. Dein Konto legt der Master an.</p></main>}
createRoot(document.getElementById('root')!).render(<App/>);
