import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
export async function prepareImage(file:File){
 if(file.size>3*1024*1024)throw Error('Bitte ein Bild mit maximal 3 MB auswählen.');
 if(!/image\/(jpeg|png|webp)/.test(file.type)&&!(/\.(jpe?g|png|webp)$/i.test(file.name)))throw Error('Bitte JPG, PNG oder WebP verwenden. HEIC-Fotos vorher als JPG exportieren.');
 const url=URL.createObjectURL(file);try{const image=new Image();await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(Error('Bild nicht lesbar. Bitte als JPG oder PNG neu speichern.'));image.src=url});
 const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');if(!ctx)throw Error('Bildverarbeitung wird vom Browser nicht unterstützt.');
 for(const edge of [1400,1100,850,600,400]){const scale=Math.min(1,edge/Math.max(image.naturalWidth,image.naturalHeight));canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);for(const quality of [.85,.7,.55,.4]){const data=canvas.toDataURL('image/jpeg',quality);if(data.startsWith('data:image/jpeg;base64,')&&data.length<=400000)return data}}
 throw Error('Bild konnte nicht verkleinert werden. Bitte anderes Foto auswählen.');}finally{URL.revokeObjectURL(url)}
}
function Post({post,data,act,busy}:{post:any,data:any,act:any,busy:boolean}){const [comment,setComment]=useState('');const remove=(id?:string)=>{if(window.confirm(id?'Kommentar löschen?':'Beitrag mit allen Kommentaren löschen?'))act('wallDelete',{post:post.id,comment:id})};return <article className="panel wall-post"><div className="list-row"><div><strong>{post.name}</strong><small>{new Date(post.date).toLocaleString('de-DE')}</small></div>{(data.admin||post.user===data.user.userId)&&<Button variant="outline" disabled={busy} onClick={()=>remove()}>Löschen</Button>}</div>{post.image&&<img className="wall-image" src={post.image} alt={post.text||'Foto aus der Bonanzbar'} loading="lazy"/>}{post.text&&<p className="wall-text">{post.text}</p>}<h3>Kommentare ({post.comments.length})</h3>{post.comments.map((c:any)=><div className="wall-comment" key={c.id}><strong>{c.name}</strong><p className="wall-text">{c.text}</p>{(data.admin||c.user===data.user.userId)&&<Button variant="ghost" disabled={busy} onClick={()=>remove(c.id)}>Kommentar löschen</Button>}</div>)}<form className="event-form" onSubmit={async e=>{e.preventDefault();if(await act('wallComment',{post:post.id,text:comment}))setComment('')}}><label>Dein Kommentar<Textarea required maxLength={1000} value={comment} onChange={e=>setComment(e.target.value)}/></label><Button disabled={busy||!comment.trim()}>Kommentieren</Button></form></article>}
export default function SocialWall({data,act,busy}:{data:any,act:any,busy:boolean}){const [text,setText]=useState(''),[image,setImage]=useState(''),[error,setError]=useState(''),[preparing,setPreparing]=useState(false);if(!data)return null;return <><div className="section-head"><div><span className="eyebrow">EURE MOMENTE</span><h2>Social Wall</h2><p>Bilder teilen und miteinander ins Gespräch kommen.</p></div></div><div className="panel"><p className="footnote">Beiträge sind für angemeldete Nutzer sichtbar.</p><form className="event-form" onSubmit={async e=>{e.preventDefault();if(await act('wallPost',{text,image})){setText('');setImage('')}}}><label>Dein Beitrag<Textarea maxLength={2000} placeholder="Was war dein Highlight?" value={text} onChange={e=>setText(e.target.value)}/></label><label className="file-picker">Bild hinzufügen<input disabled={preparing||busy} type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;setPreparing(true);setError('');setImage('');try{setImage(await prepareImage(f))}catch(err){setError((err as Error).message)}finally{setPreparing(false)}}}/></label>{preparing&&<p>Bild wird vorbereitet …</p>}{image&&<div><img className="wall-preview" src={image} alt="Bildvorschau"/><Button type="button" variant="outline" onClick={()=>setImage('')}>Bild entfernen</Button></div>}{error&&<p role="alert">{error}</p>}<Button disabled={busy||preparing||(!text.trim()&&!image)}>Beitrag veröffentlichen</Button></form></div><div className="wall-feed">{(data.wall||[]).map((post:any)=><Post key={post.id} post={post} data={data} act={act} busy={busy}/>)}</div>{!data.wall?.length&&<p>Noch keine Beiträge. Teile den ersten Moment!</p>}</>}
